### ISSUE TITLE
excuse me！！I want to know how to summarize my own video？

### ISSUE THREAD

**Issue by Mei0211** [Daegonny/static-video-summary#1]

**Comment by Daegonny** [comment]
There are two type of summaries that can be created. One of them uses histograms and it is on the file sheena.py and the other uses the saliency feature and it is on the fine sheena_sal.py. More information can be found on the paper.

These files do the summary for every video on the database folder. To do so for just a single video, you could alter the final part of the file  and remove the for. Then you pass the path of the video you want the summary:

> for video in range(size_videos):
  print("Video: "+str(video+start))
  video_frames = get_video_frames("../database/v"+str(video+start)+".mpg", True)
  diffs = get_diffs(video_frames)
  m_diffs = np.mean(diffs)
  s_diffs = np.std(diffs)
  t = m_diffs + s_diffs
  key_frames = get_key_frames(video_frames, diffs, t)
  key_frames = remove_similar(key_frames, t)
  save_frames(key_frames ,"../auto-summary/v"+str(video+start)+"/")
